all: gcd quick_sort quick_sort_pred str_to_int lazy_prime lazy_3_5 partial_function

gcd: gcd.hs
	ghci $^ <<< "run"

quick_sort: quick_sort.hs
	ghci $^ <<< "run"

quick_sort_pred: quick_sort_pred.hs
	ghci $^ <<< "run"

str_to_int: str_to_int.hs
	ghci $^ <<< "run"

lazy_prime: lazy_prime.hs
	ghci $^ <<< "run"

lazy_3_5: lazy_3_5.hs
	ghci $^ <<< "run"

partial_function: partial_function.hs
	ghci $^ <<< "run"
