all: animals divide_zero fibonacci matrix my_average read_matrix two_dim_sum unless xor

animals: animals.io
	io $^

divide_zero: divide_zero.io
	io $^

fibonacci: fibonacci.io
	io $^

guess: guess.io
	io $^

matrix: matrix.io
	io $^

my_average: my_average.io
	io $^

read_matrix: read_matrix.io
	io $^

two_dim_sum: two_dim_sum.io
	io $^

unless: unless.io
	io $^

xor: xor.io
	io $^
