all:
	make chores
	make factorial
	make movies
	make sizer

chores: chores.scala
	scala $^

factorial: factorial.scala
	scala $^

kids: kids.scala
	scala $^

movies: movies.scala
	scala $^

sizer: sizer.scala
	scala $^
