all: actor builder coroutine future list_syntax phonebook xml

actor: actor.io
	io $^
builder: builder.io
	io $^
coroutine: coroutine.io
	io $^
future: future.io
	io $^
list_syntax: list_syntax.io
	io $^
phonebook: phonebook.io
	io $^
xml: xml.io
	io $^
