all: double list_ex ttt

double:
	erl -compile double.erl &&\
	erl -noshell -s double main -s init stop

list_ex:
	erl -compile list_ex.erl &&\
	erl -noshell -s list_ex main -s init stop

ttt:
	erl -compile ttt.erl &&\
	erl -noshell -s ttt main -s init stop
