all: exam_all_even exam_reverse exam_color_tuple exam_gugu exam_map

exam_all_even: exam_all_even.hs
	ghci $^ <<< "run"

exam_reverse: exam_reverse.hs
	ghci $^ <<< "run"

exam_color_tuple: exam_color_tuple.hs
	ghci $^ <<< "run"

exam_gugu: exam_gugu.hs
	ghci $^ <<< "gugu"

exam_map: exam_map.hs
	ghci $^ <<< "run"
