all:
	make for_loop
	make ruby_for_loop
	make while

	make constructor

	make compass
	make employee

	make nice
	make ring

compass: compass.scala
	scala $^

constructor: constructor.scala
	scala $^

employee: employee.scala
	scala $^

for_loop: for_loop.scala
	scala $^

nice: nice.scala
	scala $^

ring: ring.scala
	scala $^

ruby_for_loop: ruby_for_loop.scala
	scala $^

ttt: ttt.scala
	scala $^

while: while.scala
	scala $^
